# JPA
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clone_tmon?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create

# Static resource & Live reload
---
spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    cache: false
  mvc:
    static-path-pattern: /static/**
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false

---
# Mail
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(ItniJfK3tnaQQ2klks7mVk3yNWPSZTe8)
    password: ENC(2Apb4GChU4gu9qhhjqwOPNg361eh3J0/)
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Jasypt
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

# Port
server:
  port: 8080
