# JPA
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clone_tmon?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: 'update'

# Static resource & Live reload
---
spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    cache: false
  mvc:
    static-path-pattern: /static/**
  devtools:
    livereload:
      enabled: false
  freemarker:
    cache: false
  profiles:
    include: oauth


---
# Mail
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(ItniJfK3tnaQQ2klks7mVk3yNWPSZTe8)
    password: ENC(2Apb4GChU4gu9qhhjqwOPNg361eh3J0/)
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
---
# Jasypt
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
---
# Port
server:
  port: 8080

---
# OAuth
oauth:
  google:
    client-id: ENC(qTVXCT0HlWyOwm8wkgD4yCKbN/2ENSATQdCumFgjxmAahM5YRhztoPGfFRMncNvVJq+tyWqmML0ptz63lzH4yoLgHVmqvPX8mIaty2F0LkngiM4RSR+6ZQ==)
    client-secret: ENC(HgV+CH71ZrsYmmpSG6CQ+j8I9pS6rJtTpo3iCHMtCybGp+5FjLLUYg==)
    api-url: https://www.googleapis.com/oauth2/v2
  kakao:
    client-id: ENC(mfN0JsuWY9mITzLpzug3TXWVSsJ2MRRSOxUpozb+bMzywfN1kQT+OPYI15IgYw2T)
    api-url: https://kapi.kakao.com/v1